CLASS lhc_ZI_SALES_YJKIM_U_2 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.

    METHODS CREATORDERNUM FOR DETERMINE ON SAVE
      IMPORTING KEYS FOR ZI_SALES_YJKIM_U_2~CREATORDERNUM.
    METHODS ALL_CREAT FOR MODIFY
      IMPORTING KEYS FOR ACTION ZI_SALES_YJKIM_U_2~ALL_CREAT.

ENDCLASS.

CLASS lhc_ZI_SALES_YJKIM_U_2 IMPLEMENTATION.


  METHOD CREATORDERNUM.

    READ ENTITIES OF ZI_SALES_YJKIM_U_2 IN LOCAL MODE
   ENTITY ZI_SALES_YJKIM_U_2
    FIELDS ( SALESORDER STATUS )
    WITH CORRESPONDING #( KEYS )
   RESULT DATA(LT_SALES).

    DELETE LT_SALES WHERE SALESORDER IS NOT INITIAL.
    CHECK LT_SALES IS NOT INITIAL.

    SELECT SINGLE FROM ZTSALES_YJKIM_U FIELDS MAX( SALESORDER )  INTO @DATA(ORDER_T_MAX).

    IF ORDER_T_MAX IS INITIAL.
      ORDER_T_MAX = '1000000000'.
    ENDIF.

    LOOP AT LT_SALES ASSIGNING FIELD-SYMBOL(<FS_SALES>).
      ORDER_T_MAX = ORDER_T_MAX + 1.
      <FS_SALES>-SALESORDER = ORDER_T_MAX.
      <FS_SALES>-STATUS     = 'S'.
    ENDLOOP.

    MODIFY ENTITIES OF ZI_SALES_YJKIM_U_2 IN LOCAL MODE
      ENTITY ZI_SALES_YJKIM_U_2
        UPDATE FIELDS ( STATUS SALESORDER )
        WITH VALUE #( FOR LS_ORDERS IN LT_SALES ( %TKY          = Ls_ORDERS-%TKY
                                                   STATUS       = Ls_ORDERS-STATUS
                                                   SALESORDER   = LS_ORDERS-SALESORDER ) ).

  ENDMETHOD.





  METHOD All_Creat.

      READ ENTITIES OF ZI_SALES_YJKIM_U_2 IN LOCAL MODE
   ENTITY ZI_SALES_YJKIM_U_2
    ALL FIELDS WITH CORRESPONDING #( KEYS )
   RESULT DATA(LT_SALES).

  ENDMETHOD.

ENDCLASS.
