CLASS lhc_ZI_SALES_YJKIM_D DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.

    METHODS GET_INSTANCE_AUTHORIZATIONS FOR INSTANCE AUTHORIZATION
      IMPORTING KEYS REQUEST REQUESTED_AUTHORIZATIONS FOR ZI_SALES_YJKIM_D RESULT RESULT.

    METHODS GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
      IMPORTING REQUEST REQUESTED_AUTHORIZATIONS FOR ZI_SALES_YJKIM_D RESULT RESULT.

    METHODS CREATORDERNUM FOR DETERMINE ON SAVE
      IMPORTING KEYS FOR ZI_SALES_YJKIM_D~CREATORDERNUM.

ENDCLASS.

CLASS lhc_ZI_SALES_YJKIM_D IMPLEMENTATION.

  METHOD GET_INSTANCE_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD CREATORDERNUM.

      READ ENTITIES OF ZI_SALES_YJKIM_D IN LOCAL MODE
     ENTITY ZI_SALES_YJKIM_D
      FIELDS ( SALESORDER STATUS )
      WITH CORRESPONDING #( KEYS )
     RESULT DATA(LT_SALES).

    DELETE LT_SALES WHERE SALESORDER IS NOT INITIAL.
    CHECK LT_SALES IS NOT INITIAL.

    SELECT SINGLE FROM ZTSALES_YJKIM_U FIELDS MAX( SALESORDER )  INTO @DATA(ORDER_T_MAX).
    "Get max travel ID from draft table
    SELECT SINGLE FROM ZDSALES_YJKIM_U FIELDS MAX( SALESORDER ) INTO @DATA(ORDER_D_MAX).
    IF ORDER_D_MAX > ORDER_T_MAX.
      ORDER_T_MAX = ORDER_D_MAX .
    ENDIF.

    IF ORDER_T_MAX IS INITIAL.
      ORDER_T_MAX = '1000000000'.
    ENDIF.

    DATA LV_NUM TYPE ZI_SALES_YJKIM_U-SALESORDER.
    LOOP AT LT_SALES ASSIGNING FIELD-SYMBOL(<FS_SALES>) WHERE ORDERTYPE NE ''
                                                          AND STATUS    EQ '' .
      ORDER_T_MAX = ORDER_T_MAX + 1.
      <FS_SALES>-SALESORDER = ORDER_T_MAX.
      <FS_SALES>-STATUS     = 'S'.
    ENDLOOP.

    CHECK <FS_SALES>-SALESORDER IS ASSIGNED.

    MODIFY ENTITIES OF ZI_SALES_YJKIM_D IN LOCAL MODE
      ENTITY ZI_SALES_YJKIM_D
        UPDATE FIELDS ( STATUS SALESORDER )
        WITH VALUE #( FOR LS_ORDERS IN LT_SALES ( %TKY          = Ls_ORDERS-%TKY
                                                   STATUS       = Ls_ORDERS-STATUS
                                                   SALESORDER   = LS_ORDERS-SALESORDER ) ).

  ENDMETHOD.

ENDCLASS.

CLASS lsc_ZI_SALES_YJKIM_D DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_SAVER.
  PROTECTED SECTION.

    METHODS SAVE_MODIFIED REDEFINITION.

    METHODS CLEANUP_FINALIZE REDEFINITION.

ENDCLASS.

CLASS lsc_ZI_SALES_YJKIM_D IMPLEMENTATION.

  METHOD SAVE_MODIFIED.
  ENDMETHOD.

  METHOD CLEANUP_FINALIZE.
  ENDMETHOD.

ENDCLASS.
