CLASS LHC_ITEM DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.

  PRIVATE SECTION.

    METHODS COPYCREATORDERNUM FOR DETERMINE ON SAVE
      IMPORTING KEYS FOR Item~COPYCREATORDERNUM.
    METHODS CREATEITEMNO FOR DETERMINE ON MODIFY
      IMPORTING KEYS FOR Item~CREATEITEMNO.
    METHODS MATCHECK FOR VALIDATE ON SAVE
      IMPORTING KEYS FOR Item~MATCHECK.
    METHODS TotalAMT FOR DETERMINE ON MODIFY
      IMPORTING KEYS FOR Item~TotalAMT.
*    METHODS calculateTotalPrice FOR DETERMINE ON MODIFY
*      IMPORTING KEYS FOR Item~calculateTotalPrice.

ENDCLASS.

CLASS LHC_ITEM IMPLEMENTATION.

  METHOD COPYCREATORDERNUM.

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
       ENTITY Item
        BY \_PARENT
        FIELDS ( SALESORDER )
        WITH CORRESPONDING #( KEYS )
        RESULT DATA(LT_PARENT)
        LINK DATA(LINKS).

    MODIFY ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
      ENTITY Item
        UPDATE FIELDS ( STATUS SALESORDER )
        WITH VALUE #( FOR LINK IN LINKS ( %TKY         = LINK-SOURCE-%TKY
                                          STATUS       = 'S'
                                          SALESORDER   = LT_PARENT[ KEY ID %TKY = LINK-TARGET-%TKY ]-SALESORDER ) ).

  ENDMETHOD.

  METHOD CREATEITEMNO.

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
    ENTITY Item
      BY \_PARENT
      ALL FIELDS
      WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_PARENT)
    LINK DATA(LT_LINKS).

    DATA LT_UPDATE TYPE TABLE FOR UPDATE ZR_SALES_YJKIM_HDR\\Item.

    LOOP AT LT_PARENT INTO DATA(LS_PARENT).

      READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
        ENTITY Sales
          BY \_Child
          FIELDS ( ITEMNO )
        WITH VALUE #( ( %TKY = LS_PARENT-%TKY ) )
        RESULT DATA(LT_ALL_ITEMS).

      DATA(LV_MAX_NO) = REDUCE I( INIT MAX = 0
                                   FOR ITEM IN LT_ALL_ITEMS
                                   NEXT MAX = COND #( WHEN ITEM-ITEMNO > MAX THEN ITEM-ITEMNO ELSE MAX ) ).

      LOOP AT LT_LINKS INTO DATA(LS_LINK) WHERE TARGET-%TKY = LS_PARENT-%TKY.
        LV_MAX_NO += 10.
        APPEND VALUE #( %TKY = LS_LINK-SOURCE-%TKY ITEMNO = LV_MAX_NO ) TO LT_UPDATE.
      ENDLOOP.

    ENDLOOP.

    MODIFY ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
      ENTITY Item
        UPDATE FIELDS ( ITEMNO )
        WITH LT_UPDATE.

  ENDMETHOD.

  METHOD MATCHECK.

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
       ENTITY Item
         FIELDS ( MATNR ITEMNO )
         WITH CORRESPONDING #( KEYS )
       RESULT DATA(LT_ITEMS).

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
      ENTITY Item
        BY \_PARENT
        ALL FIELDS
        WITH CORRESPONDING #( KEYS )
      RESULT DATA(LT_PARENT)
      LINK DATA(ITEM_PARENT_LINKS).

    LOOP AT LT_ITEMS INTO DATA(LS_ITEMS).

      " 1단계: 먼저 상태 리셋 (msg 없이)
      APPEND VALUE #( %TKY = LS_ITEMS-%TKY %STATE_AREA = 'VALIDATE_MATNR' ) TO REPORTED-ITEM.

      " 2단계: 조건에 맞으면 실제 메시지 추가
      IF LS_ITEMS-MATNR IS INITIAL.

        APPEND VALUE #( %TKY = LS_ITEMS-%TKY ) TO FAILED-ITEM.

        APPEND VALUE #(
          %TKY        = LS_ITEMS-%TKY
          %STATE_AREA = 'VALIDATE_MATNR'
          %MSG        = NEW_MESSAGE_WITH_TEXT(
                          TEXT     = |아이템 { LS_ITEMS-ITEMNO }: 자재번호를 입력해주세요.|
                          SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
          %PATH = VALUE #(
            Sales-%TKY = ITEM_PARENT_LINKS[ KEY ID SOURCE-%TKY = LS_ITEMS-%TKY ]-TARGET-%TKY
          )
          %ELEMENT-MATNR = IF_ABAP_BEHV=>MK-ON
        ) TO REPORTED-ITEM.

      ENDIF.

    ENDLOOP.

*    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
*        ENTITY Item
*          FIELDS ( MATNR ITEMNO )
*          WITH CORRESPONDING #( KEYS )
*        RESULT DATA(LT_ITEMS).
*
*    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
*      ENTITY Item
*        BY \_PARENT
*        ALL FIELDS
*        WITH CORRESPONDING #( KEYS )
*      RESULT DATA(LT_PARENT)
*      LINK DATA(ITEM_PARENT_LINKS).
*
*    LOOP AT LT_ITEMS INTO DATA(LS_ITEMS).
*
*      IF LS_ITEMS-MATNR IS INITIAL.
*
*        APPEND VALUE #( %TKY = LS_ITEMS-%TKY ) TO FAILED-ITEM.
*
*        APPEND VALUE #(
*          %TKY      = LS_ITEMS-%TKY
*          %MSG      = NEW_MESSAGE_WITH_TEXT(
*                   TEXT     = |아이템 { LS_ITEMS-ITEMNO }: 자재번호를 입력해주세요.|
*                   SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
*          %PATH = VALUE #(
*            Sales-%TKY = ITEM_PARENT_LINKS[ KEY ID SOURCE-%TKY = LS_ITEMS-%TKY ]-TARGET-%TKY
*          )
*          %ELEMENT-MATNR = IF_ABAP_BEHV=>MK-ON
*        ) TO REPORTED-ITEM.
*
*      ENDIF.
*
*    ENDLOOP.


  ENDMETHOD.

*  METHOD calculateTotalPrice.
*
*    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
*      ENTITY Item
*        FIELDS ( MENGE NETAMOUNT )
*        WITH CORRESPONDING #( KEYS )
*      RESULT DATA(LT_ITEMS).
*
*    MODIFY ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
*      ENTITY Item
*        UPDATE FIELDS ( TOTAMOUNT )
*        WITH VALUE #( FOR LS_ITEM IN LT_ITEMS
*                       ( %TKY       = LS_ITEM-%TKY
*                         TOTAMOUNT  = LS_ITEM-MENGE * LS_ITEM-NETAMOUNT ) )
*        FAILED DATA(LT_FAILED)
*        REPORTED DATA(LT_REPORTED).
*
*  ENDMETHOD.

  METHOD TotalAMT.

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
      ENTITY Item
        FIELDS ( MENGE NETAMOUNT ITEMNO )
        WITH CORRESPONDING #( KEYS )
      RESULT DATA(LT_ITEMS).

    DATA(LV_SUM_DRAFT) = REDUCE DECFLOAT34( INIT S = 0 FOR LS IN LT_ITEMS NEXT S = S + ( LS-NETAMOUNT * LS-MENGE ) ).



    MODIFY ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
      ENTITY Item
        UPDATE FIELDS ( TOTAMOUNT )
        WITH VALUE #( FOR LS_ITEM IN LT_ITEMS
                       ( %TKY       = LS_ITEM-%TKY
                         TOTAMOUNT  = LV_SUM_DRAFT ) )
        FAILED DATA(LT_FAILED)
        REPORTED DATA(LT_REPORTED).

    DATA(PS_ITEM) = VALUE #( LT_ITEMS[ 1 ] OPTIONAL ).

    " ★ 여기서 바로 부모(Header) 총액도 같이 계산해서 넣어버림
    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
      ENTITY Item
        BY \_PARENT
        ALL FIELDS
        WITH CORRESPONDING #( KEYS )
      RESULT DATA(LT_PARENT)
      LINK DATA(LT_LINKS).

    LOOP AT LT_PARENT INTO DATA(LS_PARENT).

      " Draft에 있는 Item들의 합
      SELECT   A~TOTAMOUNT ,
               A~ITEMNO
        FROM ZDSALES_U_I AS A INNER JOIN ZDSALES_U_H AS B
        ON A~PUUID = B~UUID
        WHERE B~UUID = @LS_PARENT-UUID
        INTO TABLE @DATA(LT_DRAFT).

      SELECT SUM( A~TOTAMOUNT )
        FROM ZDSALES_U_I AS A INNER JOIN ZDSALES_U_H AS B
        ON A~PUUID = B~UUID
        WHERE B~UUID   EQ  @LS_PARENT-UUID
          AND A~ITEMNO NE  @PS_ITEM-ITEMNO
        INTO  @DATA(LV_DRAFT_AMT).

      " Active에 있는데, Draft엔 없는 Item들만 (중복 제거)
      SELECT SUM( A~TOTAMOUNT )
        FROM ZTSALES_U_I AS A  INNER JOIN ZTSALES_U_H AS B
          ON A~PUUID   EQ B~UUID
       WHERE B~UUID    EQ @LS_PARENT-UUID
         AND NOT EXISTS (  SELECT * FROM ZDSALES_U_I AS D
                           WHERE A~PUUID EQ D~PUUID )
        INTO @DATA(LV_SUM_ACTIVE_ONLY).


      TRY.
          DATA(LO_CLIENT) = CL_WEB_HTTP_CLIENT_MANAGER=>CREATE_BY_HTTP_DESTINATION(
            CL_HTTP_DESTINATION_PROVIDER=>CREATE_BY_URL(
              'https://api.frankfurter.dev/v2/rates?base=USD&quotes=KRW'
            )
          ).

          DATA(LO_REQUEST) = LO_CLIENT->GET_HTTP_REQUEST( ).
          DATA(LO_RESPONSE) = LO_CLIENT->EXECUTE( IF_WEB_HTTP_CLIENT=>GET ).
          DATA(LV_JSON) = LO_RESPONSE->GET_TEXT( ).
        CATCH CX_HTTP_DEST_PROVIDER_ERROR
          CX_WEB_HTTP_CLIENT_ERROR INTO DATA(LX).
      ENDTRY.


      TYPES:BEGIN OF TY_RESULT,
              RATE TYPE STRING,
            END OF TY_RESULT.

      DATA: lt_RESULT TYPE STANDARD TABLE OF TY_RESULT.

      /UI2/CL_JSON=>DESERIALIZE(
          EXPORTING
           JSON = LV_JSON
          CHANGING
           DATA = lt_RESULT ).
      " ... 파싱 로직

      DATA(LV_RATE) = lt_RESULT[ 1 ]-RATE.


      DATA(LV_SUM) = ( LV_SUM_DRAFT + LV_DRAFT_AMT +  LV_SUM_ACTIVE_ONLY ) * LV_RATE.

      MODIFY ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
        ENTITY Sales
          UPDATE FIELDS ( TOTAMOUNT WAERK )
          WITH VALUE #( ( %TKY = LS_PARENT-%TKY TOTAMOUNT = LV_SUM WAERK = 'KRW'  ) ).
*
    ENDLOOP.




  ENDMETHOD.

ENDCLASS.

CLASS lhc_ZR_SALES_YJKIM_HDR DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.

    METHODS GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
      IMPORTING REQUEST REQUESTED_AUTHORIZATIONS FOR SALES RESULT RESULT.
    METHODS CREATORDERNUM FOR DETERMINE ON SAVE
      IMPORTING KEYS FOR SALES~CREATORDERNUM.
    METHODS VDCUSTOMER FOR VALIDATE ON SAVE
      IMPORTING KEYS FOR SALES~VDCUSTOMER.
*    METHODS SUMAMT FOR DETERMINE ON SAVE
*      IMPORTING KEYS FOR SALES~SUMAMT.
ENDCLASS.

CLASS lhc_ZR_SALES_YJKIM_HDR IMPLEMENTATION.

  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD CREATORDERNUM.

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
         ENTITY Sales
          FIELDS ( SALESORDER STATUS )
          WITH CORRESPONDING #( KEYS )
         RESULT DATA(LT_SALES).

    DELETE LT_SALES WHERE SALESORDER IS NOT INITIAL.
    CHECK LT_SALES IS NOT INITIAL.

    SELECT SINGLE FROM ZTSALES_U_H FIELDS MAX( SALESORDER )  INTO @DATA(ORDER_T_MAX).
    "Get max travel ID from draft table
    SELECT SINGLE FROM ZDSALES_U_H FIELDS MAX( SALESORDER ) INTO @DATA(ORDER_D_MAX).
    IF ORDER_D_MAX > ORDER_T_MAX.
      ORDER_T_MAX = ORDER_D_MAX .
    ENDIF.

    IF ORDER_T_MAX IS INITIAL.
      ORDER_T_MAX = '1000000000'.
    ENDIF.

    DATA LV_NUM TYPE ZI_SALES_YJKIM_U-SALESORDER.
    LOOP AT LT_SALES ASSIGNING FIELD-SYMBOL(<FS_SALES>) WHERE ORDERTYPE NE ''
                                                          AND STATUS    EQ '' .
      ORDER_T_MAX = ORDER_T_MAX + 1.
      <FS_SALES>-SALESORDER = ORDER_T_MAX.
      <FS_SALES>-STATUS     = 'S'.
    ENDLOOP.

    CHECK <FS_SALES>-SALESORDER IS ASSIGNED.

    MODIFY ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
      ENTITY Sales
        UPDATE FIELDS ( STATUS SALESORDER )
        WITH VALUE #( FOR LS_ORDERS IN LT_SALES ( %TKY          = Ls_ORDERS-%TKY
                                                   STATUS       = Ls_ORDERS-STATUS
                                                   SALESORDER   = LS_ORDERS-SALESORDER ) ).

  ENDMETHOD.

  METHOD VDCUSTOMER.

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
    ENTITY Sales
     FIELDS ( CUSTOMER_ID )
     WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_SALES).

    DATA LT_CUSTOMERS TYPE SORTED TABLE OF /DMO/CUSTOMER WITH UNIQUE KEY CUSTOMER_ID.

    "optimization of DB select: extract distinct non-initial customer IDs
    LT_CUSTOMERS = CORRESPONDING #( LT_SALES DISCARDING DUPLICATES MAPPING CUSTOMER_ID = CUSTOMER_ID EXCEPT * ).
    DELETE LT_CUSTOMERS WHERE CUSTOMER_ID IS INITIAL.

    IF LT_CUSTOMERS IS NOT INITIAL.
      "check if customer ID exists
      SELECT FROM /DMO/CUSTOMER FIELDS CUSTOMER_ID
                                FOR ALL ENTRIES IN @LT_CUSTOMERS
                                WHERE CUSTOMER_ID = @LT_CUSTOMERS-CUSTOMER_ID
        INTO TABLE @DATA(VALID_CUSTOMERS).
    ENDIF.

    "raise msg for non existing and initial customer id
    LOOP AT LT_SALES INTO DATA(LS_SALES).
      APPEND VALUE #(  %TKY        = LS_SALES-%TKY
                       %STATE_AREA = 'VALIDATE_CUSTOMER'
                     ) TO REPORTED-Sales.

      IF LS_SALES-CUSTOMER_ID IS  INITIAL.
        APPEND VALUE #( %TKY = LS_SALES-%TKY ) TO FAILED-Sales.

        APPEND VALUE #( %TKY        = LS_SALES-%TKY
                        %STATE_AREA = 'VALIDATE_CUSTOMER'
                        %MSG        = NEW /DMO/CM_FLIGHT_MESSAGES(
                                        TEXTID   = /DMO/CM_FLIGHT_MESSAGES=>ENTER_CUSTOMER_ID
                                        SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
                        %ELEMENT-CUSTOMER_ID = IF_ABAP_BEHV=>MK-ON
                      ) TO REPORTED-Sales.

      ELSEIF LS_SALES-CUSTOMER_ID IS NOT INITIAL AND NOT LINE_EXISTS( VALID_CUSTOMERS[ CUSTOMER_ID = LS_SALES-CUSTOMER_ID ] ).
        APPEND VALUE #(  %TKY = LS_SALES-%TKY ) TO FAILED-Sales.

        APPEND VALUE #(  %TKY        = LS_SALES-%TKY
                         %STATE_AREA = 'VALIDATE_CUSTOMER'
                         %MSG        = NEW /DMO/CM_FLIGHT_MESSAGES(
                                         CUSTOMER_ID = LS_SALES-CUSTOMER_ID
                                         TEXTID      = /DMO/CM_FLIGHT_MESSAGES=>CUSTOMER_UNKOWN
                                         SEVERITY    = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
                         %ELEMENT-CUSTOMER_ID = IF_ABAP_BEHV=>MK-ON
                      ) TO REPORTED-Sales.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.

*  METHOD SUMAMT.
*
*    LOOP AT KEYS INTO DATA(LS_KEY).
*
*      " Draft에 있는 Item들의 합
*      SELECT SUM( A~TOTAMOUNT ) AS TOTAL
*        FROM ZDSALES_U_I AS A INNER JOIN ZDSALES_U_H AS B
*        ON A~UUID = B~UUID
*        WHERE B~UUID = @LS_KEY-UUID
*        INTO TABLE @DATA(LT_DRAFT_ITEMS).
*
*      " Active에 있는데, Draft엔 없는 Item들만 (중복 제거)
*      SELECT SUM( A~TOTAMOUNT ) AS TOTAL
*        FROM ZTSALES_U_I AS A  INNER JOIN ZTSALES_U_H AS B
*          ON A~UUID = B~UUID
*       WHERE B~UUID = @LS_KEY-UUID
*         AND NOT EXISTS ( SELECT 1 FROM ZDSALES_U_I AS D
*                            WHERE D~UUID = A~UUID  )
*        INTO @DATA(LV_SUM_ACTIVE_ONLY).
*
*      DATA(LV_SUM_DRAFT) = REDUCE DECFLOAT34( INIT S = 0 FOR LS IN LT_DRAFT_ITEMS NEXT S = S + LS-TOTAL ).
*      DATA(LV_SUM) = LV_SUM_DRAFT + LV_SUM_ACTIVE_ONLY.
*
*      MODIFY ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
*        ENTITY Sales
*          UPDATE FIELDS ( TOTAMOUNT WAERK )
*          WITH VALUE #( ( %TKY = LS_KEY-%TKY TOTAMOUNT = LV_SUM  WAERK     = 'KRW' ) ).
*
*    ENDLOOP.

*  ENDMETHOD.



ENDCLASS.
