CLASS lhc_ZI_SALES_YJKIM DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.



  PRIVATE SECTION.
    METHODS GET_INSTANCE_AUTHORIZATIONS FOR INSTANCE AUTHORIZATION
      IMPORTING KEYS REQUEST REQUESTED_AUTHORIZATIONS FOR ZI_SALES_YJKIM RESULT RESULT.

    METHODS GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
      IMPORTING REQUEST REQUESTED_AUTHORIZATIONS FOR ZI_SALES_YJKIM RESULT RESULT.

    METHODS ORDERSAVE FOR DETERMINE ON SAVE
      IMPORTING KEYS FOR ZI_SALES_YJKIM~ORDERSAVE.

    METHODS GET_INSTANCE_FEATURES FOR INSTANCE FEATURES
      IMPORTING KEYS REQUEST REQUESTED_FEATURES FOR ZI_SALES_YJKIM RESULT RESULT.

    METHODS SET_STATUS_PRO FOR MODIFY
      IMPORTING KEYS FOR ACTION ZI_SALES_YJKIM~SET_STATUS_PRO RESULT RESULT.

ENDCLASS.

CLASS lhc_ZI_SALES_YJKIM IMPLEMENTATION.

  METHOD GET_INSTANCE_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD ORDERSAVE.

    READ ENTITIES OF ZI_SALES_YJKIM IN LOCAL MODE
     ENTITY ZI_SALES_YJKIM
      FIELDS ( SALESORDER STATUS )
      WITH CORRESPONDING #( KEYS )
     RESULT DATA(LT_SALES).

    DELETE LT_SALES WHERE SALESORDER IS NOT INITIAL.
    CHECK LT_SALES IS NOT INITIAL.

    SELECT SINGLE FROM ZTSALES_YJKIM_U FIELDS MAX( SALESORDER )  INTO @DATA(ORDER_T_MAX).
    "Get max travel ID from draft table
    SELECT SINGLE FROM ZDSALES_YJKIM_U FIELDS MAX( SALESORDER ) INTO @DATA(ORDER_D_MAX).
    IF ORDER_D_MAX > ORDER_T_MAX.
      ORDER_T_MAX = ORDER_D_MAX .
    ENDIF.

    IF ORDER_T_MAX IS INITIAL.
      ORDER_T_MAX = '1000000000'.
    ENDIF.

    DATA LV_NUM TYPE ZI_SALES_YJKIM-SALESORDER.
    LOOP AT LT_SALES ASSIGNING FIELD-SYMBOL(<FS_SALES>) WHERE ORDER_TYPE NE ''
                                                          AND STATUS    EQ '' .
      ORDER_T_MAX = ORDER_T_MAX + 1.
      <FS_SALES>-SALESORDER = ORDER_T_MAX.
      <FS_SALES>-STATUS     = 'S'.
    ENDLOOP.

    CHECK <FS_SALES>-SALESORDER IS ASSIGNED.

    MODIFY ENTITIES OF ZI_SALES_YJKIM IN LOCAL MODE
      ENTITY ZI_SALES_YJKIM
        UPDATE FIELDS ( STATUS SALESORDER )
        WITH VALUE #( FOR LS_ORDERS IN LT_SALES (  SALESORDER        = Ls_ORDERS-SALESORDER
                                                   STATUS            = Ls_ORDERS-STATUS ) ).

  ENDMETHOD.

  METHOD GET_INSTANCE_FEATURES.

    READ ENTITIES OF ZI_SALES_YJKIM IN LOCAL MODE
    ENTITY ZI_SALES_YJKIM
    FIELDS (  SALESORDER ) WITH CORRESPONDING #(  KEYS )
    RESULT DATA(LT_SALES).

  ENDMETHOD.

  METHOD SET_STATUS_PRO.
    DATA(LV_DATA) = 'N'.

  ENDMETHOD.

ENDCLASS.

