CLASS lhc_ZI_SALES_YJKIM_U DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.

  PRIVATE SECTION.

    METHODS GET_INSTANCE_AUTHORIZATIONS FOR INSTANCE AUTHORIZATION
      IMPORTING KEYS REQUEST REQUESTED_AUTHORIZATIONS FOR ZI_SALES_YJKIM_U RESULT RESULT.

    METHODS GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
      IMPORTING REQUEST REQUESTED_AUTHORIZATIONS FOR ZI_SALES_YJKIM_U RESULT RESULT.

    METHODS CREATORDERNUM FOR DETERMINE ON SAVE
      IMPORTING KEYS FOR ZI_SALES_YJKIM_U~CREATORDERNUM.
    METHODS UPLOADEXCEL FOR MODIFY
      IMPORTING KEYS FOR ACTION ZI_SALES_YJKIM_U~UPLOADEXCEL RESULT RESULT.
    METHODS GETEXCHANGERATE FOR MODIFY
      IMPORTING KEYS FOR ACTION ZI_SALES_YJKIM_U~GETEXCHANGERATE.
*      //RESULT RESULT.


*    METHODS SETSTATUSTOOPEN FOR DETERMINE ON MODIFY
*      IMPORTING KEYS FOR ZI_SALES_YJKIM_U~SETSTATUSTOOPEN.

*    METHODS GET_INSTANCE_FEATURES FOR INSTANCE FEATURES
*      IMPORTING KEYS REQUEST REQUESTED_FEATURES FOR ZI_SALES_YJKIM_U RESULT RESULT.

ENDCLASS.


CLASS lhc_ZI_SALES_YJKIM_U IMPLEMENTATION.

  METHOD GET_INSTANCE_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD CREATORDERNUM.

    READ ENTITIES OF ZI_SALES_YJKIM_U IN LOCAL MODE
     ENTITY ZI_SALES_YJKIM_U
      FIELDS ( SALESORDER STATUS )
      WITH CORRESPONDING #( KEYS )
     RESULT DATA(LT_SALES).

    DELETE LT_SALES WHERE SALESORDER IS NOT INITIAL.
    CHECK LT_SALES IS NOT INITIAL.

    SELECT SINGLE FROM ZTSALES_YJKIM_U FIELDS MAX( SALESORDER )  INTO @DATA(ORDER_T_MAX).
    "Get max travel ID from draft table
    SELECT SINGLE FROM ZDSALES_YJKIM_U FIELDS MAX( SALESORDER ) INTO @DATA(ORDER_D_MAX).
    IF ORDER_D_MAX > ORDER_T_MAX.
      ORDER_T_MAX = ORDER_D_MAX .
    ENDIF.

    IF ORDER_T_MAX IS INITIAL.
      ORDER_T_MAX = '1000000000'.
    ENDIF.

    DATA LV_NUM TYPE ZI_SALES_YJKIM_U-SALESORDER.
    LOOP AT LT_SALES ASSIGNING FIELD-SYMBOL(<FS_SALES>) WHERE ORDERTYPE NE ''
                                                          AND STATUS    EQ '' .
      ORDER_T_MAX = ORDER_T_MAX + 1.
      <FS_SALES>-SALESORDER = ORDER_T_MAX.
      <FS_SALES>-STATUS     = 'S'.
    ENDLOOP.

    CHECK <FS_SALES>-SALESORDER IS ASSIGNED.

    MODIFY ENTITIES OF ZI_SALES_YJKIM_U IN LOCAL MODE
      ENTITY ZI_SALES_YJKIM_U
        UPDATE FIELDS ( STATUS SALESORDER )
        WITH VALUE #( FOR LS_ORDERS IN LT_SALES ( %TKY          = Ls_ORDERS-%TKY
                                                   STATUS       = Ls_ORDERS-STATUS
                                                   SALESORDER   = LS_ORDERS-SALESORDER ) ).
  ENDMETHOD.


*  METHOD setStatusToOpen.

*    READ ENTITIES OF ZI_SALES_YJKIM_U IN LOCAL MODE
*   ENTITY ZI_SALES_YJKIM_U
*     FIELDS ( SALESORDER )
*     WITH CORRESPONDING #( KEYS )
*   RESULT DATA(LT_ORDERS)
*   FAILED DATA(READ_FAILED).
*
*    "If overall travel status is already set, do nothing, i.e. remove such instances
*    DELETE LT_ORDERS WHERE SALESORDER IS NOT INITIAL.
*    CHECK LT_ORDERS IS NOT INITIAL.
*
*    "else set overall travel status to open ('O')
*    LOOP AT LT_ORDERS ASSIGNING FIELD-SYMBOL(<FS_SALES>).
*      <FS_SALES>-Status = 'O'.
*    ENDLOOP.
*
*    MODIFY ENTITIES OF ZI_SALES_YJKIM_U IN LOCAL MODE
*      ENTITY ZI_SALES_YJKIM_U
*        UPDATE FIELDS ( STATUS )
*        WITH VALUE #( FOR Ls_ORDERS IN LT_ORDERS ( %TKY          = Ls_ORDERS-%TKY
*                                                   STATUS        = Ls_ORDERS-STATUS ) ).

*  ENDMETHOD.

* METHOD GET_INSTANCE_FEATURES.

*    READ ENTITIES OF ZI_SALES_YJKIM_U IN LOCAL MODE
*    ENTITY ZI_SALES_YJKIM_U
*    FIELDS ( SALESORDER STATUS ) WITH CORRESPONDING #( KEYS )
*    RESULT DATA(LT_SALES).

*    RESULT = VALUE #( FOR LS_SALES IN LT_SALES
*                      (  %TKY = LS_SALES-%TKY
*                         %FEATURES-%FIELD-Salesorder = IF_ABAP_BEHV=>FC-F-READ_ONLY ) ).


*  ENDMETHOD.

  METHOD UPLOADEXCEL.

    TYPES: BEGIN OF TY_EXCEL_ROW,
             ORDERTYPE     TYPE ZTSALES_YJKIM_U-ORDER_TYPE,
             SOLDTOPARTY   TYPE ZTSALES_YJKIM_U-SOLD_TO_PARTY,
             NETAMOUNT     TYPE ZTSALES_YJKIM_U-NETAMOUNT,
             WAERK         TYPE ZTSALES_YJKIM_U-WAERK,
             CREATION_DATE TYPE ZTSALES_YJKIM_U-CREATION_DATE,

           END OF TY_EXCEL_ROW.

    DATA LT_EXCEL_ROWS TYPE STANDARD TABLE OF TY_EXCEL_ROW WITH EMPTY KEY.

    LOOP AT KEYS ASSIGNING FIELD-SYMBOL(<KEY>).

      DATA(LV_ATTACHMENT) = <KEY>-%PARAM-_StreamProperties-ATTACHMENT.
      DATA(LV_MIME_TYPE)  = <KEY>-%PARAM-_StreamProperties-MIME_TYPE.
      DATA(LV_FILE_NAME)  = <KEY>-%PARAM-_StreamProperties-FILE_NAME.
      DATA: LV_ERR TYPE C.

      TRY.
          " 현재 시스템에서 XCO가 가능할 때만 사용
          DATA(LO_DOCUMENT) = XCO_CP_XLSX=>DOCUMENT->FOR_FILE_CONTENT(
                                IV_FILE_CONTENT = LV_ATTACHMENT ).

          DATA(LO_READ_ACCESS) = LO_DOCUMENT->READ_ACCESS( ).
          DATA(LO_WORKSHEET)   = LO_READ_ACCESS->GET_WORKBOOK( )->WORKSHEET->AT_POSITION( 1 ).

          DATA(LO_SELECTION) = XCO_CP_XLSX_SELECTION=>PATTERN_BUILDER->SIMPLE_FROM_TO(
            )->FROM_COLUMN( XCO_CP_XLSX=>COORDINATE->FOR_ALPHABETIC_VALUE( 'A' )
            )->FROM_ROW( XCO_CP_XLSX=>COORDINATE->FOR_NUMERIC_VALUE( 2 )
            )->TO_COLUMN( XCO_CP_XLSX=>COORDINATE->FOR_ALPHABETIC_VALUE( 'D' )
            )->GET_PATTERN( ).

          LO_WORKSHEET->SELECT( LO_SELECTION )->ROW_STREAM(

            )->OPERATION->WRITE_TO( REF #( LT_EXCEL_ROWS )
            )->EXECUTE( ).

        CATCH CX_ROOT INTO DATA(LX_EXCEL).
          APPEND VALUE #( %CID = <KEY>-%CID ) TO FAILED-ZI_SALES_YJKIM_U.
          APPEND VALUE #(
            %CID = <KEY>-%CID
            %MSG = NEW_MESSAGE_WITH_TEXT(
                     SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR
                     TEXT     = LX_EXCEL->GET_TEXT( ) )
          ) TO REPORTED-ZI_SALES_YJKIM_U.
          CONTINUE.
      ENDTRY.

      DATA LT_CREATE TYPE TABLE FOR CREATE ZI_SALES_YJKIM_U.



      LOOP AT LT_EXCEL_ROWS INTO DATA(LS_EXCEL_ROWS).
        LS_EXCEL_ROWS-CREATION_DATE = CL_ABAP_CONTEXT_INFO=>GET_SYSTEM_DATE(  ).
        IF LS_EXCEL_ROWS-CREATION_DATE IS INITIAL.
          LV_ERR = ABAP_TRUE.
          APPEND VALUE #(
          %CID             = |cid{ SY-TABIX }|
          %MSG             = NEW_MESSAGE_WITH_TEXT(
                  SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR
                  TEXT     = |{ SY-TABIX } 'REATIONDATE 는 필수 입력입니다. ' | )  )
          TO REPORTED-ZI_SALES_YJKIM_U.


        ELSE.
*          IF LS_EXCEL_ROWS-NETAMOUNT NE 0.
*            DATA(LV_AMT) = CL_ABAP_AMOUNT=>SQL_CURRENCY_AMOUNT( AMOUNT    = LS_EXCEL_ROWS-NETAMOUNT
*                                                        CURRENCY = LS_EXCEL_ROWS-WAERK
*                                                        ).
*          ENDIF.

          APPEND VALUE #(
           %CID         = |cid{ SY-TABIX }|
           ORDERTYPE    = LS_EXCEL_ROWS-ORDERTYPE
           SOLDTOPARTY  = LS_EXCEL_ROWS-SOLDTOPARTY
           NETAMOUNT    = LS_EXCEL_ROWS-NETAMOUNT
           WAERK        = LS_EXCEL_ROWS-WAERK
           CREATIONDATE = LS_EXCEL_ROWS-CREATION_DATE
          ) TO LT_CREATE.
        ENDIF.

      ENDLOOP.

      CHECK LV_ERR IS INITIAL.

      MODIFY ENTITIES OF ZI_SALES_YJKIM_U IN LOCAL MODE
        ENTITY ZI_SALES_YJKIM_U
          CREATE FIELDS ( ORDERTYPE SOLDTOPARTY NETAMOUNT WAERK CREATIONDATE
          ) WITH LT_CREATE
          MAPPED   DATA(EML_MAPPED)
          FAILED   DATA(EML_FAILED)
          REPORTED DATA(EML_REPORTED).

    ENDLOOP.

  ENDMETHOD.

  METHOD GETEXCHANGERATE.

    READ ENTITIES OF ZI_SALES_YJKIM_U IN LOCAL MODE
    ENTITY ZI_SALES_YJKIM_U
    ALL FIELDS WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_SALES).

    TRY.
        DATA(LO_CLIENT) = CL_WEB_HTTP_CLIENT_MANAGER=>CREATE_BY_HTTP_DESTINATION(
          CL_HTTP_DESTINATION_PROVIDER=>CREATE_BY_URL(
            'https://api.frankfurter.dev/v2/rates?base=USD&quotes=KRW'
          )
        ).

        DATA(LO_REQUEST) = LO_CLIENT->GET_HTTP_REQUEST( ).
        DATA(LO_RESPONSE) = LO_CLIENT->EXECUTE( IF_WEB_HTTP_CLIENT=>GET ).
        DATA(LV_JSON) = LO_RESPONSE->GET_TEXT( ).
      CATCH CX_HTTP_DEST_PROVIDER_ERROR
        CX_WEB_HTTP_CLIENT_ERROR INTO DATA(LX).
    ENDTRY.


    TYPES:BEGIN OF TY_RESULT,
            RATE TYPE STRING,
          END OF TY_RESULT.

    DATA: lt_RESULT TYPE STANDARD TABLE OF TY_RESULT.

    /UI2/CL_JSON=>DESERIALIZE(
        EXPORTING
         JSON = LV_JSON
        CHANGING
         DATA = lt_RESULT ).
    " ... 파싱 로직

    DATA(LV_RATE) = lt_RESULT[ 1 ]-RATE.
    APPEND VALUE #(
        %TKY = KEYS[ 1 ]-%TKY
        %MSG = NEW_MESSAGE_WITH_TEXT(
        SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-information
        TEXT     = |현재 USD/KRW: { LV_RATE }|
      )
    ) TO REPORTED-ZI_SALES_YJKIM_U.

*    RESULT = VALUE #(  FOR LS_SALE IN LT_SALES
*                       ( %TKY = LS_SALE-%TKY ) ).
  ENDMETHOD.

ENDCLASS.

CLASS lSc_ZI_SALES_YJKIM_U DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_SAVER.
  PROTECTED SECTION.
    METHODS SAVE_MODIFIED REDEFINITION.
ENDCLASS.

CLASS lSc_ZI_SALES_YJKIM_U IMPLEMENTATION.
  METHOD SAVE_MODIFIED .

    CHECK CREATE-ZI_SALES_YJKIM_U IS NOT INITIAL.

    LOOP AT CREATE-ZI_SALES_YJKIM_U INTO DATA(LS_DATA).

      UPDATE ZtSALES_YJKIM_U  SET SALESORDER = @LS_DATA-Salesorder
                                   WHERE UUID = @LS_DATA-UUID.

    ENDLOOP.


  ENDMETHOD.

ENDCLASS.
