CLASS ZBP_I_SALES_YJKIM_U_2
 DEFINITION PUBLIC
 FINAL FOR BEHAVIOR OF ZI_SALES_YJKIM_U_2 CREATE PUBLIC.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.

CLASS ZBP_I_SALES_YJKIM_U_2 IMPLEMENTATION.
ENDCLASS.

