CLASS LHC_ITEM DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.

  PRIVATE SECTION.

    METHODS COPYCREATORDERNUM FOR DETERMINE ON SAVE
      IMPORTING KEYS FOR Item~COPYCREATORDERNUM.
    METHODS CREATEITEMNO FOR DETERMINE ON MODIFY
      IMPORTING KEYS FOR Item~CREATEITEMNO.

ENDCLASS.

CLASS LHC_ITEM IMPLEMENTATION.

  METHOD COPYCREATORDERNUM.

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
       ENTITY Item
        BY \_PARENT
        FIELDS ( SALESORDER )
        WITH CORRESPONDING #( KEYS )
        RESULT DATA(LT_PARENT)
        LINK DATA(LINKS).

    MODIFY ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
      ENTITY Item
        UPDATE FIELDS ( STATUS SALESORDER )
        WITH VALUE #( FOR LINK IN LINKS ( %TKY         = LINK-SOURCE-%TKY
                                          STATUS       = 'S'
                                          SALESORDER   = LT_PARENT[ KEY ID %TKY = LINK-TARGET-%TKY ]-SALESORDER ) ).

  ENDMETHOD.

  METHOD CREATEITEMNO.

  READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
  ENTITY Item
    BY \_PARENT
    ALL FIELDS
    WITH CORRESPONDING #( keys )
  RESULT DATA(lt_parent)
  LINK DATA(lt_links).

    DATA LT_UPDATE TYPE TABLE FOR UPDATE ZR_SALES_YJKIM_HDR\\Item.

    LOOP AT LT_PARENT INTO DATA(LS_PARENT).

      " draft 포함 전체 item 재조회 (parent uuid 기준)
      READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
        ENTITY Sales
          BY \_Child
          FIELDS ( ITEMNO )
        WITH VALUE #( ( %TKY = LS_PARENT-%TKY ) )
        RESULT DATA(LT_ALL_ITEMS).

      DATA(LV_MAX_NO) = REDUCE I( INIT MAX = 0
                                   FOR ITEM IN LT_ALL_ITEMS
                                   NEXT MAX = COND #( WHEN ITEM-ITEMNO > MAX THEN ITEM-ITEMNO ELSE MAX ) ).

      LOOP AT LT_LINKS INTO DATA(LS_LINK) WHERE TARGET-%TKY = LS_PARENT-%TKY.
        LV_MAX_NO += 10.
        APPEND VALUE #( %TKY = LS_LINK-SOURCE-%TKY ITEMNO = LV_MAX_NO ) TO LT_UPDATE.
      ENDLOOP.

    ENDLOOP.

    MODIFY ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
      ENTITY Item
        UPDATE FIELDS ( ITEMNO )
        WITH LT_UPDATE.

  ENDMETHOD.

ENDCLASS.

CLASS lhc_ZR_SALES_YJKIM_HDR DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.

    METHODS GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
      IMPORTING REQUEST REQUESTED_AUTHORIZATIONS FOR SALES RESULT RESULT.
    METHODS CREATORDERNUM FOR DETERMINE ON SAVE
      IMPORTING KEYS FOR SALES~CREATORDERNUM.

ENDCLASS.

CLASS lhc_ZR_SALES_YJKIM_HDR IMPLEMENTATION.

  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD CREATORDERNUM.

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
         ENTITY Sales
          FIELDS ( SALESORDER STATUS )
          WITH CORRESPONDING #( KEYS )
         RESULT DATA(LT_SALES).

    DELETE LT_SALES WHERE SALESORDER IS NOT INITIAL.
    CHECK LT_SALES IS NOT INITIAL.

    SELECT SINGLE FROM ZTSALES_U_H FIELDS MAX( SALESORDER )  INTO @DATA(ORDER_T_MAX).
    "Get max travel ID from draft table
    SELECT SINGLE FROM ZDSALES_U_H FIELDS MAX( SALESORDER ) INTO @DATA(ORDER_D_MAX).
    IF ORDER_D_MAX > ORDER_T_MAX.
      ORDER_T_MAX = ORDER_D_MAX .
    ENDIF.

    IF ORDER_T_MAX IS INITIAL.
      ORDER_T_MAX = '1000000000'.
    ENDIF.

    DATA LV_NUM TYPE ZI_SALES_YJKIM_U-SALESORDER.
    LOOP AT LT_SALES ASSIGNING FIELD-SYMBOL(<FS_SALES>) WHERE ORDERTYPE NE ''
                                                          AND STATUS    EQ '' .
      ORDER_T_MAX = ORDER_T_MAX + 1.
      <FS_SALES>-SALESORDER = ORDER_T_MAX.
      <FS_SALES>-STATUS     = 'S'.
    ENDLOOP.

    CHECK <FS_SALES>-SALESORDER IS ASSIGNED.

    MODIFY ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
      ENTITY Sales
        UPDATE FIELDS ( STATUS SALESORDER )
        WITH VALUE #( FOR LS_ORDERS IN LT_SALES ( %TKY          = Ls_ORDERS-%TKY
                                                   STATUS       = Ls_ORDERS-STATUS
                                                   SALESORDER   = LS_ORDERS-SALESORDER ) ).

  ENDMETHOD.

ENDCLASS.
