CLASS LHC_ITEM DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.

  PRIVATE SECTION.

    METHODS COPYCREATORDERNUM FOR DETERMINE ON SAVE
      IMPORTING KEYS FOR Item~COPYCREATORDERNUM.
    METHODS CREATEITEMNO FOR DETERMINE ON MODIFY
      IMPORTING KEYS FOR Item~CREATEITEMNO.
    METHODS MATCHECK FOR VALIDATE ON SAVE
      IMPORTING KEYS FOR Item~MATCHECK.

ENDCLASS.

CLASS LHC_ITEM IMPLEMENTATION.

  METHOD COPYCREATORDERNUM.

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
       ENTITY Item
        BY \_PARENT
        FIELDS ( SALESORDER )
        WITH CORRESPONDING #( KEYS )
        RESULT DATA(LT_PARENT)
        LINK DATA(LINKS).

    MODIFY ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
      ENTITY Item
        UPDATE FIELDS ( STATUS SALESORDER )
        WITH VALUE #( FOR LINK IN LINKS ( %TKY         = LINK-SOURCE-%TKY
                                          STATUS       = 'S'
                                          SALESORDER   = LT_PARENT[ KEY ID %TKY = LINK-TARGET-%TKY ]-SALESORDER ) ).

  ENDMETHOD.

  METHOD CREATEITEMNO.

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
    ENTITY Item
      BY \_PARENT
      ALL FIELDS
      WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_PARENT)
    LINK DATA(LT_LINKS).

    DATA LT_UPDATE TYPE TABLE FOR UPDATE ZR_SALES_YJKIM_HDR\\Item.

    LOOP AT LT_PARENT INTO DATA(LS_PARENT).

      READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
        ENTITY Sales
          BY \_Child
          FIELDS ( ITEMNO )
        WITH VALUE #( ( %TKY = LS_PARENT-%TKY ) )
        RESULT DATA(LT_ALL_ITEMS).

      DATA(LV_MAX_NO) = REDUCE I( INIT MAX = 0
                                   FOR ITEM IN LT_ALL_ITEMS
                                   NEXT MAX = COND #( WHEN ITEM-ITEMNO > MAX THEN ITEM-ITEMNO ELSE MAX ) ).

      LOOP AT LT_LINKS INTO DATA(LS_LINK) WHERE TARGET-%TKY = LS_PARENT-%TKY.
        LV_MAX_NO += 10.
        APPEND VALUE #( %TKY = LS_LINK-SOURCE-%TKY ITEMNO = LV_MAX_NO ) TO LT_UPDATE.
      ENDLOOP.

    ENDLOOP.

    MODIFY ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
      ENTITY Item
        UPDATE FIELDS ( ITEMNO )
        WITH LT_UPDATE.

  ENDMETHOD.

  METHOD MATCHECK.

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
    ENTITY Item
     FIELDS ( MATNR ITEMNO )
     WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_ITEMS).

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
    ENTITY Item
      BY \_PARENT
      ALL FIELDS
      WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_PARENT)
    LINK DATA(LT_LINKS).

    LOOP AT LT_ITEMS INTO DATA(LS_ITEMS).



      IF LS_ITEMS-MATNR IS INITIAL.

        APPEND VALUE #( %TKY = LS_ITEMS-%TKY ) TO FAILED-Item.

        APPEND VALUE #( %TKY        = LS_ITEMS-%TKY
*                        %STATE_AREA = 'VALIDATE_MATNR'
                        %MSG        = NEW_MESSAGE_WITH_TEXT(
                                        TEXT     = |아이템 { LS_ITEMS-ITEMNO }: 자재번호를 입력해주세요.|
                                        SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
                        %ELEMENT-MATNR = IF_ABAP_BEHV=>MK-ON
                      ) TO REPORTED-Item.
      ENDIF.
    ENDLOOP.


  ENDMETHOD.

ENDCLASS.

CLASS lhc_ZR_SALES_YJKIM_HDR DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.

    METHODS GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
      IMPORTING REQUEST REQUESTED_AUTHORIZATIONS FOR SALES RESULT RESULT.
    METHODS CREATORDERNUM FOR DETERMINE ON SAVE
      IMPORTING KEYS FOR SALES~CREATORDERNUM.
    METHODS VDCUSTOMER FOR VALIDATE ON SAVE
      IMPORTING KEYS FOR SALES~VDCUSTOMER.

ENDCLASS.

CLASS lhc_ZR_SALES_YJKIM_HDR IMPLEMENTATION.

  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD CREATORDERNUM.

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
         ENTITY Sales
          FIELDS ( SALESORDER STATUS )
          WITH CORRESPONDING #( KEYS )
         RESULT DATA(LT_SALES).

    DELETE LT_SALES WHERE SALESORDER IS NOT INITIAL.
    CHECK LT_SALES IS NOT INITIAL.

    SELECT SINGLE FROM ZTSALES_U_H FIELDS MAX( SALESORDER )  INTO @DATA(ORDER_T_MAX).
    "Get max travel ID from draft table
    SELECT SINGLE FROM ZDSALES_U_H FIELDS MAX( SALESORDER ) INTO @DATA(ORDER_D_MAX).
    IF ORDER_D_MAX > ORDER_T_MAX.
      ORDER_T_MAX = ORDER_D_MAX .
    ENDIF.

    IF ORDER_T_MAX IS INITIAL.
      ORDER_T_MAX = '1000000000'.
    ENDIF.

    DATA LV_NUM TYPE ZI_SALES_YJKIM_U-SALESORDER.
    LOOP AT LT_SALES ASSIGNING FIELD-SYMBOL(<FS_SALES>) WHERE ORDERTYPE NE ''
                                                          AND STATUS    EQ '' .
      ORDER_T_MAX = ORDER_T_MAX + 1.
      <FS_SALES>-SALESORDER = ORDER_T_MAX.
      <FS_SALES>-STATUS     = 'S'.
    ENDLOOP.

    CHECK <FS_SALES>-SALESORDER IS ASSIGNED.

    MODIFY ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
      ENTITY Sales
        UPDATE FIELDS ( STATUS SALESORDER )
        WITH VALUE #( FOR LS_ORDERS IN LT_SALES ( %TKY          = Ls_ORDERS-%TKY
                                                   STATUS       = Ls_ORDERS-STATUS
                                                   SALESORDER   = LS_ORDERS-SALESORDER ) ).

  ENDMETHOD.

  METHOD VDCUSTOMER.

    READ ENTITIES OF ZR_SALES_YJKIM_HDR IN LOCAL MODE
    ENTITY Sales
     FIELDS ( CUSTOMER_ID )
     WITH CORRESPONDING #( KEYS )
    RESULT DATA(LT_SALES).

    DATA LT_CUSTOMERS TYPE SORTED TABLE OF /DMO/CUSTOMER WITH UNIQUE KEY CUSTOMER_ID.

    "optimization of DB select: extract distinct non-initial customer IDs
    LT_CUSTOMERS = CORRESPONDING #( LT_SALES DISCARDING DUPLICATES MAPPING CUSTOMER_ID = CUSTOMER_ID EXCEPT * ).
    DELETE LT_CUSTOMERS WHERE CUSTOMER_ID IS INITIAL.

    IF LT_CUSTOMERS IS NOT INITIAL.
      "check if customer ID exists
      SELECT FROM /DMO/CUSTOMER FIELDS CUSTOMER_ID
                                FOR ALL ENTRIES IN @LT_CUSTOMERS
                                WHERE CUSTOMER_ID = @LT_CUSTOMERS-CUSTOMER_ID
        INTO TABLE @DATA(VALID_CUSTOMERS).
    ENDIF.

    "raise msg for non existing and initial customer id
    LOOP AT LT_SALES INTO DATA(LS_SALES).
      APPEND VALUE #(  %TKY        = LS_SALES-%TKY
                       %STATE_AREA = 'VALIDATE_CUSTOMER'
                     ) TO REPORTED-Sales.

      IF LS_SALES-CUSTOMER_ID IS  INITIAL.
        APPEND VALUE #( %TKY = LS_SALES-%TKY ) TO FAILED-Sales.

        APPEND VALUE #( %TKY        = LS_SALES-%TKY
                        %STATE_AREA = 'VALIDATE_CUSTOMER'
                        %MSG        = NEW /DMO/CM_FLIGHT_MESSAGES(
                                        TEXTID   = /DMO/CM_FLIGHT_MESSAGES=>ENTER_CUSTOMER_ID
                                        SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
                        %ELEMENT-CUSTOMER_ID = IF_ABAP_BEHV=>MK-ON
                      ) TO REPORTED-Sales.

      ELSEIF LS_SALES-CUSTOMER_ID IS NOT INITIAL AND NOT LINE_EXISTS( VALID_CUSTOMERS[ CUSTOMER_ID = LS_SALES-CUSTOMER_ID ] ).
        APPEND VALUE #(  %TKY = LS_SALES-%TKY ) TO FAILED-Sales.

        APPEND VALUE #(  %TKY        = LS_SALES-%TKY
                         %STATE_AREA = 'VALIDATE_CUSTOMER'
                         %MSG        = NEW /DMO/CM_FLIGHT_MESSAGES(
                                         CUSTOMER_ID = LS_SALES-CUSTOMER_ID
                                         TEXTID      = /DMO/CM_FLIGHT_MESSAGES=>CUSTOMER_UNKOWN
                                         SEVERITY    = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
                         %ELEMENT-CUSTOMER_ID = IF_ABAP_BEHV=>MK-ON
                      ) TO REPORTED-Sales.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.

ENDCLASS.
